### PR TITLE
Build71 format

### PR DESCRIPTION
**Pull request by bhilbert4**
Scripts have been updated to use the Distortion reference file datamodel, and produce files in the appropriate format for Build 7.1 of the pipeline.

### CODE REVIEW

**Comment by nden** [comment]
@bhilbert4 Do you want to merge this?

**Comment by bhilbert4** [comment]
I have one small additional edit to one of the files, to include WFSS modes in the imaging files. Seems like I should also add NRC_FOCUS to the list. I can make the updates and recommit.

**Comment by sosey** [comment]
@bhilbert4 are you talking about the imaging mode distortion reference files or are there others?

**Comment by bhilbert4** [comment]
I'm talking about adding NRC_GRISM and NRC_TSGRISM to the exp_type list in the imaging mode reference files. The changes I made a few weeks ago when I redelivered the files.

**Comment by sosey** [comment]
I knew you added them to the distorion files, but are there other reference files they need to be added to?

**Comment by bhilbert4** [comment]
No. This is just for the little wrapper script I put together that calls the reference file creation script for each of the various modes.

**Pull request closed without merging**
