### PR TITLE
Updated to conform to model format decided upon for pipeline Build 7.1

### PR DESCRIPTION
**Pull request by bhilbert4**
Rather than returning delta v2,v3 from the reference location of the aperture, the compound astropy model now returns absolute v2,v3 values in arcseconds. 

x and y pixel values are now indexed to zero to match up with python.

Also included the small script I used to create the reference files for the imaging mode for all 10 detectors.

### CODE REVIEW

**Comment by nden** [comment]
@bhilbert4 Is this the current version? Does it need to be merged?

**Comment by bhilbert4** [comment]
No, I haven't uploaded the final code yet. Now that the reference files have been delivered and seem to be good, I'll provide the code used for them.

**Comment by nden** [comment]
Feel free to merge it when it's ready and milestone it as 7.1. Thanks!

**Comment by bhilbert4** [comment]
I've added updated scripts which use the final Build 7.1 format into pull request Build71 #19. So I'm closing this pull request to avoid confusion.

**Pull request closed without merging**
